env:
  # browser: false
  node: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/jsx-runtime
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - autofix
  - sort-imports-es6-autofix
rules: 
  semi: 
    - error
    - always
  '@typescript-eslint/no-unused-vars': error
  autofix/no-unused-vars: error
  autofix/no-console: error
  sort-imports-es6-autofix/sort-imports-es6: error
